/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator s1 = new StandardCalculator();
        s1.add(1, 2);
        System.out.println(s1.getResult());

        



    }
}
